In [7]:
# Dependencies and Setup

import pandas as pd
import numpy as np

eruptions = "Resources/eruptions.csv"
eruptions_data = pd.read_csv(eruptions)

events = "Resources/events.csv"
events_df = pd.read_csv(events)

volcano = "Resources/volcano.csv"
volcano_df = pd.read_csv(volcano)

#damage = "Resources/damage.csv"
#damage_df = pd.read_csv(damage,sep=";")

In [8]:
eruptions_data.dropna(subset=['start_year'], how='all', inplace=True)
eruptions_data['start_month'] = eruptions_data['start_month'].fillna(1)
eruptions_data['start_day'] = eruptions_data['start_day'].fillna(1)

eruptions_data.drop(eruptions_data[eruptions_data.start_year < 1800].index, inplace=True)
eruptions_data

,volcano_number,volcano_name,eruption_number,eruption_category,area_of_activity,vei,start_year,start_month,start_day,evidence_method_dating,end_year,end_month,end_day,latitude,longitude
0,266030,Soputan,22354,Confirmed Eruption,NaN,NaN,2020.0,3.0,23.0,Historical Observations,2020.0,4.0,2.0,1.112,124.737
1,343100,San Miguel,22355,Confirmed Eruption,NaN,NaN,2020.0,2.0,22.0,Historical Observations,2020.0,2.0,22.0,13.434,-88.269
2,233020,"Fournaise, Piton de la",22343,Confirmed Eruption,NaN,NaN,2020.0,2.0,10.0,Historical Observations,2020.0,4.0,6.0,-21.244,55.708
3,345020,Rincon de la Vieja,22346,Confirmed Eruption,NaN,NaN,2020.0,1.0,31.0,Historical Observations,2020.0,4.0,17.0,10.830,-85.324
4,353010,Fernandina,22347,Confirmed Eruption,NaN,NaN,2020.0,1.0,12.0,Historical Observations,2020.0,1.0,12.0,-0.370,-91.550
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6216,252080,Witori,15022,Confirmed Eruption,NaN,4.0,1800.0,0.0,0.0,Tephrochronology,NaN,NaN,NaN,-5.576,150.516
6217,241030,Taranaki,13348,Confirmed Eruption,NaN,NaN,1800.0,0.0,0.0,Tephrochronology,NaN,NaN,NaN,-39.300,174.070
6218,390030,Deception Island,13182,Confirmed Eruption,N side caldera bay (near Telefon Bay),NaN,1800.0,0.0,0.0,Historical Observations,NaN,NaN,NaN,-63.001,-60.652
6219,344120,Concepcion,11046,Uncertain Eruption,NaN,2.0,1800.0,0.0,0.0,NaN,NaN,NaN,NaN,11.538,-85.622
6220,354031,Ticsani,11793,Confirmed Eruption,NaN,NaN,1800.0,0.0,0.0,Tephrochronology,NaN,NaN,NaN,-16.755,-70.595

In [9]:
eruptions_data.dropna(subset=['end_year'], how='all', inplace=True)
eruptions_data['end_month'] = eruptions_data['end_month'].fillna(1)
eruptions_data['end_day'] = eruptions_data['end_day'].fillna(1)

In [10]:
#Converting start date columns to strings and concatenating them to a datetime value.

eruptions_data['start_year'] = eruptions_data['start_year'].apply(lambda x: int(x))
eruptions_data['start_month'] = eruptions_data['start_month'].apply(lambda x: int(x))
eruptions_data['start_day'] = eruptions_data['start_day'].apply(lambda x: int(x))

eruptions_data['start_year'] = eruptions_data['start_year'].astype(str)
eruptions_data['start_month'] = eruptions_data['start_month'].astype(str)
eruptions_data['start_day'] = eruptions_data['start_day'].astype(str)

eruptions_data["start date"] = eruptions_data["start_year"] + '.' + eruptions_data["start_month"] + '.' + eruptions_data["start_day"]

In [11]:
#Converting end date columns to strings and concatenating them to a datetime value.
eruptions_data['end_year'] = eruptions_data['end_year'].apply(lambda x: int(x))
eruptions_data['end_month'] = eruptions_data['end_month'].apply(lambda x: int(x))
eruptions_data['end_day'] = eruptions_data['end_day'].apply(lambda x: int(x))

eruptions_data['end_year'] = eruptions_data['end_year'].astype(str)
eruptions_data['end_month'] = eruptions_data['end_month'].astype(str)
eruptions_data['end_day'] = eruptions_data['end_day'].astype(str)

eruptions_data["end date"] = eruptions_data["end_year"] + '.' + eruptions_data["end_month"] + '.' + eruptions_data["end_day"]

In [12]:
#Dropping uneccessary columns
clean_eruption_data = eruptions_data.drop(columns=['area_of_activity', 'evidence_method_dating','eruption_number','vei','eruption_category','start_year','start_month','start_day','end_year','end_month','end_day'])

In [14]:
clean_eruption_data

,volcano_number,volcano_name,latitude,longitude,start date,end date
0,266030,Soputan,1.112,124.737,2020.3.23,2020.4.2
1,343100,San Miguel,13.434,-88.269,2020.2.22,2020.2.22
2,233020,"Fournaise, Piton de la",-21.244,55.708,2020.2.10,2020.4.6
3,345020,Rincon de la Vieja,10.830,-85.324,2020.1.31,2020.4.17
4,353010,Fernandina,-0.370,-91.550,2020.1.12,2020.1.12
...,...,...,...,...,...,...
6202,233020,"Fournaise, Piton de la",-21.244,55.708,1800.11.2,1800.11.8
6203,273030,Mayon,13.257,123.685,1800.10.30,1800.10.31
6204,353020,Wolf,0.020,-91.350,1800.8.21,1800.8.21
6205,382030,San Jorge,38.650,-28.080,1800.6.24,1800.6.25
6209,332040,Hualalai,19.692,-155.870,1800.0.0,1801.0.0